# Generated by Django 4.0.1 on 2022-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_authors_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
